version: 1.0.0

services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_DB='test'
      - POSTGRES_USER='root'
      - POSTGRES_PASSWORD='fsaFafnaskfjnsajkfnasjfsafsaf7as8fasf87as87'
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

